# Generated by Django 4.0.8 on 2024-02-24 09:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default=None, max_length=400, null=True, upload_to='videoes/')),
                ('titel', models.CharField(max_length=500, null=True)),
                ('slug_v', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='titel', unique=True)),
            ],
        ),
    ]
